name: Generate Controllers PlantUML

on:
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Generate controllers.puml
        run: |
          mkdir -p scripts doc
          cat > scripts/generate_controllers_puml.py << 'PY'
# (Paste the Python script from my previous message here)
PY
          python3 scripts/generate_controllers_puml.py src/main/java doc/controllers.puml
          ls -lah doc

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: controllers.puml
          path: doc/controllers.puml
